### PR TITLE
Modernize download function

### PR DESCRIPTION
**Pull request by bjesuiter**
Hello @kt-12, 

since I need a download function for my next project in deno, I found your package and thought, I might as well contribute some things to this library which makes it even more versatile. 
So, this should be the first PR from me for this repo in a series of prs. 

This first pr should clean up the state of the lib and modernize it to the current state of deno. 
It replaces deprecated Deno APIs and improves code idiomacy for deno. 

Outlook for the next PR: 
I want to integrate a "downloadStreaming" method which would allow the user to download a file directly to storage, 
without buffering it in memory, because buffering in memory does only work until 4 GB. 

If you have questions or disagree with some code style, feel free to discuss these with me. 
I'm simply here to improve the package :)

### CODE REVIEW

**Comment by kt-12** [comment]
@bjesuiter I agree with you. It's been a while i haven't visited this and i can see a lot has changed in Deno from the time i last used it.  
Almost all commits look pretty much convincing to me. Let me test them and then we can releases them as v2.0.0

**Comment by kt-12** [comment]
@bjesuiter   I have reviewed the code. Changes looks fine to me. Can you add 2 more update to this pull request. 

1. Update [.travis.yml](https://github.com/deno-module/download/blob/master/.travis.yml) script command to match the new test file. 
2. Update code snippets from [README.md](https://github.com/deno-module/download/blob/master/README.md) file to match with the new code standards.

**Comment by bjesuiter** [comment]
Yes , I can add these two things in the next days :)

**Comment by bjesuiter** [comment]
@kt-12 I've updated the PR as you requested :)

**Comment by IJsLauw** [comment]
What happened here? I approve, please keep everything merging along :)

**Comment by kt-12** [comment]
Thank you @bjesuiter, this is now the new version and sorry for the delay (got caught up in personal issues).

**Comment by kt-12** [comment]
> modernize_download_function

To be frank got caught up in lot of personal things. But this is now released.

**Comment by IJsLauw** [comment]
> > modernize_download_function
> 
> To be frank got caught up in lot of personal things. But this is now released.

Life happens sometimes like that, thanks for the quick action! @bjesuiter I saw you also have a branch for download streaming standing stand-by. Is that one ready to merge or still a work in progress?

**Comment by bjesuiter** [comment]
It's not ready yet. I was unsure whether this idea would be a good fit for this library or if it should be published in another deno module. 
I've published it as "downstream" module at https://deno.land/x/downstream@0.3.2

I have to look what my latest state is, but if I remember correctly, this downstream module should be stable.
One optional thing that's missing is an easy way to render a cli progress bar from the progress webstream which the downstream() method returns. 

But I would really like to have a review on that lib! 
if you're interested, we can think about merging it into here.

**Pull request merged**
